version: "3.9"
services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: telofundi
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./telofundi.dump:/docker-entrypoint-initdb.d/telofundi.dump
    networks:
      - telofundi_network

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    environment:
      DATABASE_URL: postgres://admin:admin123@db:5432/telofundi
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - telofundi_network

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - telofundi_network

volumes:
  db_data:

networks:
  telofundi_network:
    driver: bridge
